apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: aryazanov/pipeline/agent/fake
    context: ./fakes/.agent
    docker:
      dockerfile: Dockerfile
  - image: aryazanov/pipeline/executor/echo
    context: .
    docker:
      dockerfile: ./examples/echo/Dockerfile
deploy:
  helm:
    releases:
    - name: echo
      namespace: example-echo
      createNamespace: true
      chartPath: ./examples/echo/chart
      artifactOverrides:
        pipeline_agent:
          image: aryazanov/pipeline/agent/fake
        command-executor:
          image: aryazanov/pipeline/executor/echo