name: Publish artifacts

on:
  push:
    branches: [ main ]

jobs:       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        make build

    - name: Test
      run: |
        make test

    - name: Set env
      run: echo "RELEASE_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Container
      run: |
        make container DTAG=${{ env.RELEASE_TAG }}
  
    - name: Publish
      uses: actions/upload-artifact@v2
      with: 
        name: command-executor
        path: bin/command-executor